name: Bob`s_CI_CD
 
on: 
    push:
        branches: 
            - main
            - develop
jobs:
  my_tests: 
    runs-on: ubuntu-latest
    steps:
        - name: checkout perository
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: testing
          run: |
            python3 -m unittest tst
        - name: send telegram message on push
          uses: appleboy/telegram-action@master
          with:
            to: -1001861863113
            token: 5735366347:AAHxo3Nk7bfQyI9BQnN6wctaUvKt6cAF--U
            message: |
              ${{ github.action }} created commit
