name: Bob`s_CI_CD
 
on: 
    push:
        branches: 
            - main
            - develop
jobs:
  my_tests: 
    runs-on: ubuntu-latest
    steps:
        - name: checkout perository
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: testing
          run: |
            python3 -m unittest tst
        - name: Send notify to Telegam
          uses: KaMeHb-UA/telegram-ci-notify-action@v5
          if: ${{ always() }}
          with:
            status: ${{ steps.5.outcome }}
            bot-token: 5735366347:AAHxo3Nk7bfQyI9BQnN6wctaUvKt6cAF--U
            chat-id: -1001861863113
            container-name: my-org/container-name
            container-link: https://my-docker-registry.com/my-org/container-name
            skip-is-fail: true
            default-branch: $default-branch
